runtime: python3
env: flex

entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  LINKEDIN_EMAIL: $LINKEDIN_EMAIL
  LINKEDIN_PASSWORD: $LINKEDIN_PASSWORD
  SESSION_SECRET: $SESSION_SECRET

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6