runtime: python311

entrypoint: gunicorn -b :$PORT main:app --timeout 120

env_variables:
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  max_concurrent_requests: 50

network:
  session_affinity: true

inbound_services:
- warmup