version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r pyproject.toml
  pre_build:
    commands:
      - echo Pre-build phase...
      - python -c "import sys; print(sys.version)"
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app.py
    - main.py
    - enhanced_linkedin_scraper.py
    - linkedin_finder.py
    - scraper.py
    - pyproject.toml
    - templates/**/*
    - static/**/*
    - .platform/**/*
    - Procfile
    - appspec.yml
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'